version: '3'

services:
  app:
    build: ./DOCKER
    command: python djangoMongo/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/djangoMongo
    links:
      - db
    ports:
      - "8000:8000"
  db:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./db:/data/db
    restart: always